language: node_js
node_js:
  - 0.8

before_install:
- sudo apt-get update
- sudo apt-get install python-yaml
- sudo apt-get install php5-cli
- wget https://getcomposer.org/composer.phar && php composer.phar update
- cp regexes.yaml py/ua_parser/regexes.yaml
- cp regexes.yaml php/resources/regexes.yaml

script:
  - "npm test"
  - "python py/ua_parser/user_agent_parser_test.py"
  - sh -c "cd php && ../vendor/bin/phpunit"
